;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-star
	c-indent-line-or-region
	electric-newline-and-maybe-indent
	indent-for-tab-command
	org-beginning-of-line
	org-cycle
	org-end-of-line
	org-kill-line
	org-open-line
	org-return
	org-self-insert-command
	org-yank
	overwrite-mode
	sgml-slash
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	abbrev-prefix-mark
	kill-region
	org-ctrl-c-ctrl-c
	org-delete-char
	org-edit-special
	))
